from typing import Protocol


class AmazingHandBackend(Protocol):
    def connect(self, port: str, baudrate: int) -> None: ...

    def disconnect(self) -> None: ...

    def ping(self, motor_id: int) -> int | None: ...

    def set_torque(self, enabled: bool) -> None: ...

    def read_positions(self) -> dict[int, int]: ...

    def write_positions(self, positions: dict[int, int]) -> None: ...

    def latch_current_position(self) -> dict[int, int]:
        """Read every configured motor and write the same values as goals."""
        ...

    def read_temperatures(self) -> dict[int, float] | None: ...

    def read_loads(self) -> dict[int, float] | None: ...
